### ISSUE TITLE
Measures alignment - Sticking them to the axis edge

### ISSUE THREAD

**Issue by ghost** [danpanaite/flutter_radar_chart#12]
Hello,
How can I configure the labels (measures) on the chart so they stick to the axis edges?
As you can see in the image, the labels on the left have a big blank space, while the ones at the center and at the right are "sticked" 
to the axis edge.

![image](https://user-images.githubusercontent.com/73125519/110359616-4ffa6800-8003-11eb-9c3d-9a718076bf95.png)

**Comment by duongtruong12** [comment]
any information for this?

**Comment by leidig54** [comment]
same here

**Comment by danpanaite** [comment]
Hi there, apologies for the delay. Version 0.2.1 should provide a better approach for label positions. You can see the code change here:  9fa1df19ee294ac835f27420d1ecf0268048ea0e

This repository isn't actively maintained, so I encourage anyone to jump in and make contributions to address any issues.
