### ISSUE TITLE
Null Safety?

### ISSUE THREAD

**Issue by jordygarcias** [danpanaite/flutter_radar_chart#13]
Are you planning to give support for flutter 2.0?

It would be awesome if you can get it 😄

**Comment by danpanaite** [comment]
Good call! I have no real plans, but I might pick this up sometime in the near future.

I'm also accepting any PR's if you'd like to tackle it as well!

**Comment by ciamax** [comment]
Please support Flutter 2.0 and null-safety

**Comment by danpanaite** [comment]
Latest release (0.2.0) supports Flutter 2.0 and null-safety

**Comment by danpanaite** [comment]
Ah sorry just noticed #14 , thanks @jordygarcias for the PR! The changes I made was very similar to your changes.
