### ISSUE TITLE
float and double datas are not supported

### ISSUE THREAD

**Issue by xiaomiao-fong** [danpanaite/flutter_radar_chart#15]
While we were using this module, we found out that when we give the float data it threw errors, and we can see that the dataset is defined as list<list<int>>, it is very weird to not allow floats and doubles in data graphs, please fix this problem, thanks

**Comment by danpanaite** [comment]
Hi there, version 0.2.1 should now address this issue. You can view the fix here: e7a66b9389bbb6516ca4147c3802f196de443a56

FYI, this repository is not actively maintained, so I encourage anyone to make contributions on any issues found.

**Comment by xiaomiao-fong** [comment]
It worked, thanks for your help
