### ISSUE TITLE
Package not working

### ISSUE THREAD

**Issue by CobyReshef** [danpanaite/flutter_radar_chart#18]
flutter_radar_chart package is not working, not recognized.
Added to pubspec.yaml dependencies: flutter_radar_chart: ^0.2.1 - OK
Added  import 'package:flutter_radar_chart/flutter_radar_chart.dart'; - ERROR. not recognized.

this is my flutter doctor results:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 12.2.1 21D62 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by danpanaite** [comment]
Hey there, have you been able to run the /example project within this repo?

**Comment by CobyReshef** [comment]
I tested the example. it worked perfectly.
The problem is probably with my settings or code. I'll check it.
Thank you.

**Comment by danpanaite** [comment]
Okay sounds good, hope you fix it!
