### ISSUE TITLE
Problem with feature position

### ISSUE THREAD

**Issue by deadsoul44** [danpanaite/flutter_radar_chart#2]
There is a problem with feature text position. I guess as feature text becomes longer, it is positioned more away from chart.

![image](https://user-images.githubusercontent.com/31016182/74109312-7f317200-4b82-11ea-938b-06bfbcbf2dfc.png)

**Comment by danpanaite** [comment]
Hey, the label positioning is pretty hard-coded so it's far from perfect. I have added a super tiny tweak (0.1.3) that should position the left feature labels closer to the chart. Let me know if that helps. If not, we'll have to think through a better approach.

**Comment by deadsoul44** [comment]
I decided not to use radar chart. We can close this issue. Thank you.
