### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by deadsoul44** [danpanaite/flutter_radar_chart#3]
I get the following exceptions when I use radar chart.

`_RadarChartState#c3338(ticker active) was disposed with an active Ticker.`

`'package:flutter/src/widgets/framework.dart': Failed assertion: line 3867 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.`

**Comment by danpanaite** [comment]
Can't seem to reproduce this exception. Can you provide more context?

**Comment by deadsoul44** [comment]
I decided not to use radar chart. We can close this issue. Thank you.
