### ISSUE TITLE
change graph colours

### ISSUE THREAD

**Issue by leidig54** [danpanaite/flutter_radar_chart#8]
Hi danpanaite,

thanks for a great little package. are there any plans to enable colour selection for the plots?

Thanks, 

g

**Comment by danpanaite** [comment]
Hey glad you like it!

I can definitely take a look at enabling color selection, shouldn't be too much effort. I'm also open to contributions if you'd like to take a crack at it.

**Comment by danpanaite** [comment]
@leidig54 Taking a look at the options, you can tweak the color selection using the `graphColors` parameter in the `RadarChart` widget.

Let me know if that's what you were looking for.

**Comment by leidig54** [comment]
Hi Dan - I have tried that but for it to work outside of my dev environment I'll need to fork the repo. I'd love to contribute but am a total novice and suspect I'd do more harm than good!  May be a good first challenge though...

**Comment by leidig54** [comment]
Apologies - I was using RadarChart.dark as so couldn't seen the option for the graphColors parameters. Doh!
